// 多目标构建：node-functions + edge-functions + middleware.js
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import { dirname, resolve, join } from 'node:path';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const SHARED = resolve(ROOT, 'shared', 'src');
const nodeSrc = (p) => resolve(ROOT, 'node-functions', 'src', p);
const entries = (p) => resolve(ROOT, 'node-functions', 'src', 'entries', p);
const frontDist = resolve(ROOT, 'dist', 'index.html');

function sharedAlias() {
  return { '@shared': SHARED };
}

function banner() {
  return `/* EdgeOne DB Admin — generated ${new Date().toISOString()} */`;
}

export async function generateIndexHtmlModule() {
  let html = '';
  try {
    html = readFileSync(frontDist, 'utf8');
  } catch {
    console.warn('[build] dist/index.html 不存在，SPA 回落使用占位');
  }
  const body = `// GENERATED by build.mjs — do not edit.\nexport const INDEX_HTML = ${JSON.stringify(html)};\n`;
  writeFileSync(nodeSrc('generated-index-html.ts'), body, 'utf8');
}

const NODE_EXTERNAL = [
  'kerberos', '@mongodb-js/zstd', '@aws-sdk/credential-providers',
  'aws4', 'mongodb-client-encryption', 'socks', 'snappy',
  'cpu-features', 'pg-native', 'pg-cloudflare', 'bcrypt', 'iconv',
];

async function bundle({ entry, outfile, platform, target, minify = false }) {
  await build({
    entryPoints: [entry],
    outfile,
    bundle: true,
    format: 'esm',
    platform,
    target,
    minify,
    sourcemap: false,
    legalComments: 'none',
    alias: sharedAlias(),
    logLevel: 'info',
    banner: { js: banner() },
    ...(platform === 'node' ? { external: NODE_EXTERNAL } : {}),
  });
}

export async function buildAll({ minify = false } = {}) {
  const mk = (dir) => mkdirSync(dir, { recursive: true });
  await generateIndexHtmlModule();

  const targetEdge = 'es2022';
  const edgeDir = resolve(ROOT, 'edge-functions');
  const nodeDir = resolve(ROOT, 'node-functions');
  mk(edgeDir);
  mk(nodeDir);
  mk(join(edgeDir, 'api'));
  mk(join(nodeDir, 'api'));

  // 边缘函数（V8 薄）
  await bundle({ entry: entries('auth.entry.ts'), outfile: join(edgeDir, 'api', 'auth.js'), platform: 'browser', target: targetEdge, minify });
  await bundle({ entry: entries('meta.entry.ts'), outfile: join(edgeDir, 'api', 'meta.js'), platform: 'browser', target: targetEdge, minify });
  await bundle({ entry: entries('tunnel.entry.ts'), outfile: join(edgeDir, 'api', 'tunnel.js'), platform: 'browser', target: targetEdge, minify });
  await bundle({ entry: entries('spa.entry.ts'), outfile: join(edgeDir, '[[path]].js'), platform: 'browser', target: targetEdge, minify });
  await bundle({ entry: entries('middleware.entry.ts'), outfile: join(ROOT, 'middleware.js'), platform: 'browser', target: targetEdge, minify });

  // Node 厚执行器
  await bundle({ entry: entries('db.entry.ts'), outfile: join(nodeDir, 'api', 'db.js'), platform: 'node', target: 'node18', minify });

  console.log('[build] 完成 → edge-functions/, node-functions/, middleware.js');
}

if (process.argv[1] && import.meta.url === new URL(`file://${process.argv[1].replaceAll('\\', '/')}`).href) {
  buildAll({ minify: process.argv.includes('--minify') }).catch((e) => { console.error(e); process.exit(1); });
}