// backend 多目标构建：把同一套 TS 打成 EdgeOne 需要的几个产物文件。
//   edge-functions/（V8 薄）  api/{auth,meta,tunnel}.js  [[path]].js
//   node-functions/（Node 厚） api/db.js
//   根 middleware.js（edge）
// 并依据 frontend/dist/index.html 生成 backend/src/generated-index-html.ts。
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import { dirname, resolve, join } from 'node:path';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const SHARED = resolve(ROOT, 'shared', 'src');
const backend = (p) => resolve(ROOT, 'backend', p);
const frontDist = resolve(ROOT, 'frontend', 'dist', 'index.html');

function sharedAlias() {
  return { '@shared': SHARED };
}

function banner() {
  return `/* EdgeOne DB Admin — generated by backend/build.mjs ${new Date().toISOString()} */`;
}

export async function generateIndexHtmlModule() {
  let html = '';
  try {
    html = readFileSync(frontDist, 'utf8');
  } catch {
    console.warn('[build] frontend/dist/index.html 不存在，SPA 回落使用占位');
  }
  const body = `// GENERATED by backend/build.mjs — do not edit.\nexport const INDEX_HTML = ${JSON.stringify(html)};\n`;
  writeFileSync(backend('src/generated-index-html.ts'), body, 'utf8');
}

const NODE_EXTERNAL = [
  // Node 内置自动保留；以下为可选的/原生绑定模块，运行时 try/catch 兜底，不打进单文件
  'kerberos',
  '@mongodb-js/zstd',
  '@aws-sdk/credential-providers',
  'aws4',
  'mongodb-client-encryption',
  'socks',
  'snappy',
  'cpu-features',
  'pg-native',
  'pg-cloudflare',
  'bcrypt',
  'iconv',
];

async function bundle({ entry, outfile, platform, target, minify = false }) {
  const opts = {
    entryPoints: [entry],
    outfile,
    bundle: true,
    format: 'esm',
    platform,
    target,
    minify,
    sourcemap: false,
    legalComments: 'none',
    alias: sharedAlias(),
    logLevel: 'info',
    banner: { js: banner() },
  };
  if (platform === 'node') {
    opts.external = NODE_EXTERNAL;
  }
  await build(opts);
}

export async function buildAll({ minify = false } = {}) {
  const mk = (dir) => mkdirSync(dir, { recursive: true });

  await generateIndexHtmlModule();

  const targetEdge = 'es2022';
  const edgeDir = resolve(ROOT, 'edge-functions');
  const nodeDir = resolve(ROOT, 'node-functions');
  mk(edgeDir);
  mk(nodeDir);
  mk(join(edgeDir, 'api'));
  mk(join(nodeDir, 'api'));

  const entries = [
    ['auth.entry.ts', join(edgeDir, 'api', 'auth.js')],
    ['meta.entry.ts', join(edgeDir, 'api', 'meta.js')],
    ['tunnel.entry.ts', join(edgeDir, 'api', 'tunnel.js')],
  ];
  for (const [name, outfile] of entries) {
    await bundle({ entry: backend(`src/entries/${name}`), outfile, platform: 'browser', target: targetEdge, minify });
  }
  // SPA catch-all（文件内带 [[ ]] 文件名，Windows 下无碍——由构建生成）
  await bundle({ entry: backend('src/entries/spa.entry.ts'), outfile: join(edgeDir, '[[path]].js'), platform: 'browser', target: targetEdge, minify });
  // 根 middleware（edge）
  await bundle({ entry: backend('src/entries/middleware.entry.ts'), outfile: join(ROOT, 'middleware.js'), platform: 'browser', target: targetEdge, minify });

  // Node 厚执行器（含驱动），node 内置模块 external
  await bundle({ entry: backend('src/entries/db.entry.ts'), outfile: join(nodeDir, 'api', 'db.js'), platform: 'node', target: 'node18', minify });

  console.log('[build] 完成 → edge-functions/, node-functions/, middleware.js');
}

if (process.argv[1] && import.meta.url === new URL(`file://${process.argv[1].replaceAll('\\', '/')}`).href) {
  const min = process.argv.includes('--minify');
  buildAll({ minify: min }).catch((e) => {
    console.error(e);
    process.exit(1);
  });
}
