// 后端函数打包：把 functions-src/ 下的 TS 源码，分别打成 EdgeOne Pages 认得的单文件函数。
//   输出：
//     node-functions/api/db.js            （Node 运行时：直连/SSH 执行器）
//     edge-functions/api/{auth,meta,tunnel}.js （Edge 运行时：登录 / 能力表 / 隧道中继）
// 产物仅依赖 node: 内置与 Web 全局，可被平台再次打包，因此只需提交产物、由云端统一构建。
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import { dirname, resolve, join } from 'node:path';
import { mkdirSync } from 'node:fs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const SHARED = resolve(ROOT, 'shared', 'src');
const entry = (name) => resolve(ROOT, 'functions-src', 'entries', name);

// ssh2 及各家驱动可选的原生模块：打包时保持 external（运行时 Node 自带解析 + 平台 externalNodeModules 拷贝）
const NATIVE_EXTERNAL = [
  'kerberos', '@mongodb-js/zstd', '@aws-sdk/credential-providers',
  'aws4', 'mongodb-client-encryption', 'socks', 'snappy',
  'cpu-features', 'pg-native', 'pg-cloudflare', 'bcrypt', 'iconv',
];

async function bundle({ entryFile, outfile, platform, target, minify = true }) {
  await build({
    entryPoints: [entryFile],
    outfile,
    bundle: true,
    format: 'esm',
    platform,
    target,
    minify,
    sourcemap: false,
    legalComments: 'none',
    alias: { '@shared': SHARED },
    banner: { js: '/* EdgeOne DB Admin — generated by functions-src/build.mjs */' },
    ...(platform === 'node' ? { external: NATIVE_EXTERNAL } : {}),
    logLevel: 'warning',
  });
}

export async function buildFunctions({ minify = true } = {}) {
  const mk = (d) => mkdirSync(d, { recursive: true });
  mk(join(ROOT, 'node-functions', 'api'));

  // 全部作为 Node 函数输出到 node-functions/api/（Makers 已验证此目录/runtime 可用）
  const targets = [
    ['db.entry.ts', 'db.js'],
    ['auth.entry.ts', 'auth.js'],
    ['meta.entry.ts', 'meta.js'],
    ['tunnel.entry.ts', 'tunnel.js'],
  ];
  for (const [name, out] of targets) {
    await bundle({
      entryFile: entry(name),
      outfile: join(ROOT, 'node-functions', 'api', out),
      platform: 'node',
      target: 'node18',
      minify,
    });
  }
  console.log('[build] 函数产物 → node-functions/api/{db,auth,meta,tunnel}.js');
}

if (process.argv[1] && import.meta.url === new URL(`file:///${process.argv[1].replaceAll('\\', '/')}`).href) {
  buildFunctions({ minify: !process.argv.includes('--no-minify') }).catch((e) => { console.error(e); process.exit(1); });
}
