/* EdgeOne DB Admin — generated 2026-09-06T10:58:52.278Z */
function E(t){return t&&typeof t=="object"?t:typeof process<"u"&&process.env?process.env:{}}function g(t,r){let e=t.url??r??"";if(!e)return"/";if(/^https?:\/\//i.test(e))try{return new URL(e).pathname}catch{return e.split("?")[0]||"/"}return e.split("?")[0]||"/"}function R(t,r){return(t.method??r??"GET").toUpperCase()}function l(t,r){let e=t,n=e.request??t,i=n.headers?n.headers:{get:()=>null},s=r?.path??e.pathname??g(n,e.url);return{env:r?.env??E(e.env),method:r?.method??R(n,e.method),pathname:s,url:e.url??n.url??s,request:n,headers:i,data:{}}}var o=class t extends Error{code;status;detail;constructor(r,e,n){super(e),this.name="AppError",this.code=r,this.status=n?.status??c(r),this.detail=n?.detail,n?.cause!==void 0&&(this.cause=n.cause)}static badRequest(r,e){return new t("BAD_REQUEST",r,{detail:e})}static unauthorized(r="\u672A\u767B\u5F55\u6216\u767B\u5F55\u5DF2\u8FC7\u671F",e){return new t("UNAUTHORIZED",r,{detail:e})}};function c(t){switch(t){case"BAD_REQUEST":case"VALIDATION":case"SYNTAX":case"DECODE":case"PAYLOAD_TOO_LARGE":return 400;case"UNAUTHORIZED":case"TUNNEL_AUTH":case"AUTH_DB":case"AUTH_SSH":return 401;case"FORBIDDEN":case"PERMISSION":return 403;case"NOT_FOUND":case"OBJECT_NOT_FOUND":return 404;case"TIMEOUT":return 408;default:return 500}}var A={"content-type":"application/json; charset=utf-8"};function p(t,r,e="text/plain; charset=utf-8"){return new Response(r,{status:t,headers:{"content-type":e}})}function a(t,r,e){return new Response(JSON.stringify(r),{status:t,headers:{...A,...e}})}function m(t,r="INTERNAL"){let e=t instanceof o?t:new o(r,t?.message??"\u672A\u77E5\u9519\u8BEF"),n=e.status||c(e.code),i={ok:!1,error:{code:e.code,message:e.message,detail:e.detail}};return a(n,i)}function f(t,r=["POST"]){return async function(n){let i=l(n);try{if(r.length&&!r.includes(i.method))throw new o("BAD_REQUEST","\u4E0D\u652F\u6301\u7684\u65B9\u6CD5",{status:405});let s=await t(i);return s.headers.set("cache-control","no-store, max-age=0"),s}catch(s){return m(s)}}}var u=`<!doctype html>\r
<html lang="zh-CN">\r
  <head>\r
    <meta charset="UTF-8" />\r
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\r
    <title>EdgeOne DB Admin</title>\r
    <script type="module" crossorigin src="/assets/index-DtBpqetT.js"><\/script>
    <link rel="stylesheet" crossorigin href="/assets/index-C3Umr6kH.css">
  </head>\r
  <body>\r
    <div id="app"></div>\r\r
  </body>\r
</html>\r
`;function T(){return u&&u.length>0?u:'<!doctype html><html><head><meta charset="utf-8"><title>EdgeOne DB Admin</title></head><body><div id="app"></div><script>location.replace("/")<\/script></body></html>'}var h=async t=>t.pathname.startsWith("/api")?a(404,{ok:!1,error:{code:"NOT_FOUND",message:"\u63A5\u53E3\u4E0D\u5B58\u5728"}}):t.method==="HEAD"?p(200,"","text/html; charset=utf-8"):t.method!=="GET"?a(405,{ok:!1,error:{code:"BAD_REQUEST",message:"\u4E0D\u652F\u6301\u7684\u65B9\u6CD5"}}):p(200,T(),"text/html; charset=utf-8");var d=f(h,["GET","HEAD"]),B=d;var b=d,F=d;export{B as default,d as onRequest,b as onRequestGet,F as onRequestHead};
